name: Monthly Metrics for Issues Linked to Pull Requests
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 28-31 * *"

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest

    steps:
    - name: Set current day of month as env variable
      env:
        TZ: "Asia/Tokyo"
      run: |
        echo "current_datetime=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "current_day_of_month=$(date +'%-d')" >> $GITHUB_ENV

    - name: Show current date
      run: echo ${{ env.current_datetime }}   # Current datetime (JST)

    - name: Show day of month
      run: echo ${{ env.current_day_of_month }}   # Day of the month (1-31)

    - name: Is NOT the first day of the month
      if: ${{ env.current_day_of_month != 1 }}   # Run if it's not the 1st day of the month
      run: |
        echo "Today is NOT the first day of the month. Skipping job."
        exit 0

    - name: Get dates for last month
      if: ${{ env.current_day_of_month == 1 }}   # Run if it's the 1st day of the month
      run: |
        echo "Today is the first day of the month"
        echo "Fetching metrics for the last month.."

        # Calculate the first day of the last month
        first_day=$(date -d "today" +%Y-%m-01)

        # Extract year and month (YYYY-MM) for the title
        year_month=$(date -d "today" +%Y-%m)

        # Set an environment variable
        echo "first_day=$first_day" >> $GITHUB_ENV
        echo "year_month=$year_month" >> $GITHUB_ENV

    - name: Run issue-metrics tool
      if: ${{ env.current_day_of_month == 1 }}   # Run if it's the 1st day of the month
      uses: github/issue-metrics@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: "repo:mayamazaki/rails_docker is:issue linked:pr -closed:<${{ env.first_day }}"

    - name: Create issue
      if: ${{ env.current_day_of_month == 1 }}   # Run if it's the 1st day of the month
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: "Monthly Issue Metrics: ${{ env.year_month }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        content-filepath: ./issue_metrics.md
