name: Weekly issue metrics
on:
  workflow_dispatch:
  schedule:
    - cron: '30 9 3 * *'

permissions:
  issues: write
  pull-requests: read

jobs:
  build:
    name: issue metrics
    runs-on: ubuntu-latest

    steps:
    - name: Get dates for last month
      shell: bash
      run: |
        # Calculate the start (Monday) of the current week
        first_day=$(date -d "last monday" +%Y-%m-%d)

        # Calculate the end (Sunday) of the current week
        last_day=$(date -d "$first_day +6 days" +%Y-%m-%d)

        # Set an environment variable with the date range
        echo "$first_day..$last_day"
        echo "this_week=$first_day..$last_day" >> "$GITHUB_ENV"

        echo 'repo:mayamazaki/rails_docker is:"issue pr" created:${{ env.this_week }} -reason:"not planned"'

    - name: Run issue-metrics tool
      uses: github/issue-metrics@v2
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SEARCH_QUERY: 'repo:mayamazaki/rails_docker is:"issue pr" created:${{ env.this_week }} -reason:"not planned"'

    - name: Create issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: Weekly issue metrics report
        token: ${{ secrets.GITHUB_TOKEN }}
        content-filepath: ./issue_metrics.md
        # assignees: <YOUR_GITHUB_HANDLE_HERE>
